// mktg — Brand directory management
// Scaffolding, freshness assessment, context matrix.

import { join } from "node:path";
import { mkdir } from "node:fs/promises";
import {
  BRAND_FILES,
  BRAND_PROFILE_FILES,
  BRAND_APPEND_FILES,
  type BrandFile,
  type BrandFileStatus,
  type FreshnessLevel,
} from "../types";

// Brand file templates — minimal scaffolds the agent fills in
const BRAND_TEMPLATES = {
  "voice-profile.md": `# Brand Voice Profile\n\n<!-- Generated by mktg init. Fill in or let /cmo build this. -->\n\n## Voice DNA\n\n- **Tone:**\n- **Personality:**\n- **Vocabulary:**\n`,
  "positioning.md": `# Positioning & Angles\n\n<!-- Generated by mktg init. Fill in or let /cmo build this. -->\n\n## Core Positioning\n\n- **Category:**\n- **For:**\n- **Unlike:**\n- **We:**\n`,
  "audience.md": `# Audience Research\n\n<!-- Generated by mktg init. Fill in or let /cmo build this. -->\n\n## Primary Audience\n\n- **Who:**\n- **Pain points:**\n- **Watering holes:**\n`,
  "competitors.md": `# Competitive Intelligence\n\n<!-- Generated by mktg init. Fill in or let /cmo build this. -->\n\n## Competitors\n\n1.\n2.\n3.\n`,
  "keyword-plan.md": `# Keyword Plan\n\n<!-- Generated by mktg init. Fill in or let /cmo build this. -->\n\n## Priority Keywords\n\n| Keyword | Intent | Difficulty | Priority |\n|---------|--------|------------|----------|\n`,
  "creative-kit.md": `# Creative Kit\n\n<!-- Generated by mktg init. Fill in or let /cmo build this. -->\n\n## Brand Colors\n\n## Typography\n\n## Visual Style\n`,
  "stack.md": `# Marketing Stack\n\n<!-- Generated by mktg init. Tools the agent can use. -->\n\n## Available Tools\n\n- **Email:** gws\n- **Social:** playwright-cli / ply\n- **Video:** remotion\n- **Search:** exa\n- **Media:** ffmpeg\n`,
  "assets.md": `# Assets Log\n\n<!-- Append-only. Agent adds entries as assets are created. -->\n`,
  "learnings.md": `# Marketing Learnings\n\n<!-- Append-only. Agent records what worked and what didn't. -->\n`,
} as const satisfies Record<BrandFile, string>;

// Export for use by skill-lifecycle (template detection)
export { BRAND_TEMPLATES };

// Pre-compute template SHA-256 hashes for fast comparison
let _templateHashes: Record<BrandFile, string> | null = null;

const getTemplateHashes = (): Record<BrandFile, string> => {
  if (_templateHashes) return _templateHashes;
  const hashes = {} as Record<BrandFile, string>;
  for (const file of BRAND_FILES) {
    const hasher = new Bun.CryptoHasher("sha256");
    hasher.update(BRAND_TEMPLATES[file]);
    hashes[file] = hasher.digest("hex");
  }
  _templateHashes = hashes;
  return hashes;
};

// Check if file content matches the template (hasn't been customized)
export const isTemplateContent = (file: BrandFile, content: string): boolean => {
  const hashes = getTemplateHashes();
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(content);
  return hasher.digest("hex") === hashes[file];
};

// Scaffold brand/ directory — creates files that don't exist
export const scaffoldBrand = async (
  projectRoot: string,
  dryRun: boolean = false,
): Promise<{ created: BrandFile[]; skipped: BrandFile[] }> => {
  const brandDir = join(projectRoot, "brand");
  const created: BrandFile[] = [];
  const skipped: BrandFile[] = [];

  if (!dryRun) {
    // Ensure brand/ exists
    await mkdir(brandDir, { recursive: true });
  }

  const writes: Promise<void>[] = [];

  for (const file of BRAND_FILES) {
    const filePath = join(brandDir, file);
    const bunFile = Bun.file(filePath);
    const exists = await bunFile.exists();

    if (exists) {
      skipped.push(file);
    } else {
      created.push(file);
      if (!dryRun) {
        writes.push(Bun.write(filePath, BRAND_TEMPLATES[file]).then(() => {}));
      }
    }
  }

  // Parallel writes
  await Promise.all(writes);

  return { created, skipped };
};

// Freshness assessment — pure function, no side effects
export const assessFreshness = (
  modifiedMs: number,
  reviewIntervalDays: number = 30,
): FreshnessLevel => {
  const ageDays = (Date.now() - modifiedMs) / (1000 * 60 * 60 * 24);
  if (ageDays <= reviewIntervalDays) return "current";
  return "stale";
};

// Get status of all brand files in a project
export const getBrandStatus = async (
  projectRoot: string,
): Promise<BrandFileStatus[]> => {
  const brandDir = join(projectRoot, "brand");
  const statuses: BrandFileStatus[] = [];

  for (const file of BRAND_FILES) {
    const filePath = join(brandDir, file);
    const bunFile = Bun.file(filePath);
    const exists = await bunFile.exists();

    if (!exists) {
      statuses.push({ file, exists: false, freshness: "missing", ageDays: null });
      continue;
    }

    const stat = await bunFile.stat();
    const ageDays = Math.floor((Date.now() - stat.mtimeMs) / (1000 * 60 * 60 * 24));
    const isAppendOnly = (BRAND_APPEND_FILES as readonly string[]).includes(file);

    // Append-only files are always "current" if they exist
    const freshness: FreshnessLevel = isAppendOnly
      ? "current"
      : assessFreshness(stat.mtimeMs);

    statuses.push({ file, exists: true, freshness, ageDays });
  }

  return statuses;
};

// Check if brand/ directory exists
export const brandExists = async (projectRoot: string): Promise<boolean> => {
  const brandDir = join(projectRoot, "brand");
  return Bun.file(brandDir).exists();
};

// Context matrix — which brand files each skill layer needs
// Skills use this to know what context to load (progressive enhancement)
export const CONTEXT_MATRIX = {
  foundation: ["voice-profile.md", "positioning.md", "audience.md", "competitors.md"],
  strategy: ["voice-profile.md", "positioning.md", "audience.md", "competitors.md", "keyword-plan.md"],
  execution: ["voice-profile.md", "positioning.md", "audience.md", "creative-kit.md"],
  distribution: ["voice-profile.md", "audience.md", "stack.md"],
} as const satisfies Record<string, readonly BrandFile[]>;
